Repository Tugduoff/GomokuAI, pull requests merged in 2024-11, with the labels that each got.

#28 :sparkles: Repo init
  CONTRIBUTING.md
  flake.lock
  flake.nix
  pbrain-gomoku-ai
Labels: enhancement

#33 :memo: Doxygen documentation
  doc/Doxyfile
  doc/doxygen_custom.css
  flake.nix
Labels: documentation

#32 :truck: Cpp implementation
  .gitignore
  Makefile
  inc/Board.hpp
  inc/Commands.hpp
  inc/Position.hpp
  inc/Stone.hpp
  models/.gitkeep
  models/Commands.py
  pbrain-gomoku-ai
  src/Main.cpp
Labels: modifications

#34 :heavy_plus_sign: Added the AI class
  .github/workflows/work.yml
  inc/AI.hpp
Labels: ai

#36 :wrench: Fix Board class by including cstdint lib.
  inc/Board.hpp
Labels: fix bug

#40 :construction_worker: Added new github workflow for the doxygen doc d…
  .github/workflows/doc.yml
Labels: documentation, enhancement

#37 :memo: Fix documentation
  .gitignore
  README.md
  doc/Doxyfile
  doc/doxygen_custom.css
Labels: documentation

#38 :wrench: Fix ai implentation
  CONTRIBUTING.md
  flake.nix
  inc/AI.hpp
  inc/Board.hpp
  inc/CommandHandler.hpp
  inc/Commands.hpp
  src/Main.cpp
Labels: fix bug, modifications, protocol, ai

#42 :adhesive_bandage: Fix protocol
  inc/CommandHandler.hpp
  src/Main.cpp
Labels: fix bug, protocol

#43 :adhesive_bandage: Fix protocol error output instead of normal output.
  inc/CommandHandler.hpp
  src/Main.cpp
Labels: fix bug, protocol

#44 :sparkles: Ai min max
  inc/AI.hpp
  inc/CommandHandler.hpp
  inc/Position.hpp
  inc/Stone.hpp
  src/Main.cpp
Labels: enhancement, modifications, ai

#49 :sparkles: Handle a4 patterns
  inc/AI.hpp
  inc/CommandHandler.hpp
Labels: enhancement, ai

#56 :heavy_plus_sign: Added searchBoard removeMove function and logic imp…
  inc/AI.hpp
  inc/Stone.hpp
  src/Board.cpp
Labels: fix bug, ai

#58 :wrench: Board timeout fix
  inc/AI.hpp
  inc/Board.hpp
  src/Board.cpp
  tests/testBoard100Cells.txt
  tests/testBoard10Cells.txt
  tests/testBoard200Cells.txt
  tests/testBoard20Cells.txt
  tests/testBoard25Cells.txt
  tests/testBoard50Cells.txt
  tests/testBoard75Cells.txt
Labels: fix bug

#60 :wrench: Opti timeout
  Makefile
  inc/AI.hpp
  src/Board.cpp
Labels: enhancement, modifications

#67 :sparkles: Added checks for cross patterns. Needs refining with the o…
  inc/AI.hpp
  inc/Board.hpp
  inc/Line.hpp
  src/AI.cpp
  src/Board.cpp
Labels: enhancement, ai
